export enum TransactionType {
  TRANSFER = "TRANSFER",
  TRANSFER_IBAN = "TRANSFER_IBAN",
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  INTEREST = "INTEREST",
  INVESTMENT_BUY = "INVESTMENT_BUY",
  INVESTMENT_SELL = "INVESTMENT_SELL",
}
